# -*- coding: utf-8 -*-
"""Straight-to-the-point reader.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CEOUoJCorc1PZ38JdkxNb-qrzA4_O-9B
"""

import streamlit as st
from transformers import pipeline
from pypdf import PdfReader

model_pipeline = pipeline("document-question-answering", model="impira/layoutlm-document-qa")

def extract_text_from_pdf(pdf_file):
    reader = PdfReader(pdf_file)
    text = ""
    for page in reader.pages:
        text += page.extract_text()
    return text

st.title("Straight-To-The-Point Reader")
st.write("Upload your e-book and ask questions about its content!")

uploaded_file = st.file_uploader("Upload Your e-book", type="pdf")

if uploaded_file:
    with st.spinner("Processing the e-book..."):

        pdf_text = extract_text_from_pdf(uploaded_file)
    st.success("e-book uploaded and processed successfully!")

    if st.checkbox("Show Extracted Text"):
        st.write(pdf_text)

    question = st.text_input("Chat your book to get straight-to-the-point facts:")

    if question:
        with st.spinner("Finding the answer..."):

            result = model_pipeline({
                "question": question,
                "context": pdf_text
            })

        st.write("Answer:", result['answer'])
        st.write(f"Confidence Score: {result['score']:.2f}")



st.markdown(
    """
    <hr style="margin-top: 50px;">
    <div style="text-align: center; color: gray;">
        Developed by <a href="https://www.linkedin.com/in/tolulopeoyejide" target="_blank" style="text-decoration: none; color: #4CAF50;">Tolulope Oyejide</a>
    </div>
    """,
    unsafe_allow_html=True
)